In [2]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(42)
num_samples = 12000
num_features = 55

financial_features = [
    "Revenue", "Cost of Goods Sold", "Gross Profit", "Operating Expenses", "EBITDA",
    "Net Income", "Total Assets", "Total Liabilities", "Equity", "Operating Cash Flow",
    "Investing Cash Flow", "Financing Cash Flow", "Current Assets", "Current Liabilities",
    "Working Capital", "Debt to Equity Ratio", "Return on Assets", "Return on Equity",
    "Revenue Growth", "Net Profit Margin", "EBITDA Margin", "Interest Coverage Ratio",
    "Earnings per Share", "Book Value per Share", "Dividend Yield", "Price to Earnings Ratio",
    "Price to Book Ratio", "Free Cash Flow", "Capital Expenditures", "Inventory Turnover",
    "Accounts Receivable Turnover", "Accounts Payable Turnover", "Days Sales Outstanding",
    "Days Payable Outstanding", "Days Inventory Outstanding", "Asset Turnover",
    "Current Ratio", "Quick Ratio", "Cash Ratio", "Debt Ratio", "Gross Margin",
    "Operating Margin", "Net Profit Growth", "ROIC", "EBIT", "NOPAT", "Total Debt",
    "Short-term Debt", "Long-term Debt", "Market Capitalization", "Enterprise Value",
    "Dividend Payout Ratio", "Interest Expense", "Tax Rate"
]

In [4]:
financial_data = np.random.normal(loc=0, scale=1, size=(num_samples, len(financial_features)))

In [5]:
df = pd.DataFrame(financial_data, columns=financial_features)

In [6]:
df.head()

,Revenue,Cost of Goods Sold,Gross Profit,Operating Expenses,EBITDA,Net Income,Total Assets,Total Liabilities,Equity,Operating Cash Flow,...,EBIT,NOPAT,Total Debt,Short-term Debt,Long-term Debt,Market Capitalization,Enterprise Value,Dividend Payout Ratio,Interest Expense,Tax Rate
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560,...,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040,0.324084,-0.385082,-0.676922,0.611676
1,1.031000,0.931280,-0.839218,-0.309212,0.331263,0.975545,-0.479174,-0.185659,-1.106335,-1.196207,...,0.005113,-0.234587,-1.415371,-0.420645,-0.342715,-0.802277,-0.161286,0.404051,1.886186,0.174578
2,0.257550,-0.074446,-1.918771,-0.026514,0.060230,2.463242,-0.192361,0.301547,-0.034712,-1.168678,...,-0.680025,0.232254,0.293072,-0.714351,1.865775,0.473833,-1.191303,0.656554,-0.974682,0.787085
3,1.158596,-0.820682,0.963376,0.412781,0.822060,1.896793,-0.245388,-0.753736,-0.889514,-0.815810,...,0.515035,0.513786,0.515048,3.852731,0.570891,1.135566,0.954002,0.651391,-0.315269,0.758969
4,-0.772825,-0.236819,-0.485364,0.081874,2.314659,-1.867265,0.686260,-1.612716,-0.471932,1.088951,...,-0.926930,-0.059525,-3.241267,-1.024388,-0.252568,-1.247783,1.632411,-1.430141,-0.440044,0.130741

In [7]:
df.shape

(12000, 54)

In [8]:
df.to_csv("financial_data.csv", index=False)